src/main/java/pl/psalkowski/blogger/model/GenericEntity.java
package pl.psalkowski.blogger.model;

import java.io.Serializable;

public interface GenericEntity extends Serializable {
	public long getId();
}

src/main/java/pl/psalkowski/blogger/controller/SearchController.java
package pl.psalkowski.blogger.controller;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;

import pl.psalkowski.blogger.dao.ArticleDao;
import pl.psalkowski.blogger.model.Article;

@Controller
public class SearchController extends GenericController {

	@Autowired
	private ArticleDao articleDao;
	
	@RequestMapping("/search")
	public String search(@RequestParam("search") String search, Model model) {
		
		List<Article> articles = articleDao.search(search);
		
		model.addAttribute("articles", articles);
		model.addAttribute("search", search);
		return "search";
	}
}

src/main/webapp/WEB-INF/views/index.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>


Main page!	

src/main/webapp/WEB-INF/views/search.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<%@taglib uri="http://www.springframework.org/security/tags" prefix="security" %>


<h2>Search result for "${ search }"</h2>

<c:choose>
	<c:when test="${not empty articles}">
		<table>
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Author</th>
				</tr>
			</thead>
			<tbody>
				<c:forEach var="article" items="${articles}" varStatus="status">
					<tr>
						<td>${ status.index + 1 }</td>
						<td><a href="/blogger/article/show/${ article.id }">${ article.title }</a></td>
						<td>${ article.user.username }</td>
					</tr>
				</c:forEach>
			</tbody>
		</table>
	</c:when>

	<c:otherwise>
		No result
	</c:otherwise>
</c:choose>